site_name: NYC Urban Mobility Data Platform

repo_url: https://github.com/ddm18/nyc-taxi-lakehouse
repo_name: /ddm18/nyc-taxi-lakehouse
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Architecture:
      - System Overview: architecture/overview.md
      - Platform Components: architecture/components.md
      - Pipeline Execution: architecture/pipeline-execution.md
      - Deployment Topology: architecture/deployment-topology.md
      - Environment Model: architecture/environment-model.md
      - CI/CD Workflow: architecture/cicd.md
      - Repository Structure: repo-structure.md

  - ADR:
      - 001 Ingestion Model: adr/001-ingestion-model.md
      - 002 Partitioning Strategy: adr/002-partitioning-strategy.md
      - 003 Schema Contracts: adr/003-schema-contracts.md
      - 004 Data Quality: adr/004-data-quality.md
      - 005 Data Governance: adr/005-data-governance.md
      - 006 Infrastructure: adr/006-infrastructure.md
      - 007 Pipeline: adr/007-pipeline.md
      - 008 Transformation Layer: adr/008-dbt-transformation-layer.md
      - 009 Environment Topology: adr/009-environment-topology.md
      - 010 Reference Data and Geography: adr/010-reference-data-and-geography.md
      - 011 Reprocessing and Change Detection: adr/011-reprocessing-and-change-detection.md
      - 012 Data Quality Exception Handling: adr/012-data-quality-exception-handling.md
      - 013 Cloud Validation Slice: adr/013-cloud-validation-slice.md
      - 014 AWS Validation Infrastructure Operating Model: adr/014-aws-validation-infrastructure-operating-model.md
      - 015 Release and Deployment Workflow: adr/015-release-and-deployment-workflow.md

  - Discovery:
      - Data Discovery Taxi: exploration_notes/data-discovery-taxi.md
      - Data Discovery Weather: exploration_notes/data-discovery-weather.md

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - plantuml_markdown:
      format: svg_inline
      remove_inline_svg_size: true
      servers:
        - https://www.plantuml.com/plantuml
      base_dir: .
      config: docs/plantuml-config.puml
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
