select
  cast(service_type as string) as service_type,
  cast(pickup_year as int) as pickup_year,
  cast(pickup_month as int) as pickup_month,
  cast(pickup_date as date) as pickup_date,
  cast(season_name as string) as season_name,
  cast(count(*) as bigint) as trip_count,
  cast(sum(case when is_valid_trip then 1 else 0 end) as bigint) as valid_trip_count,
  cast(sum(case when is_weekend then 1 else 0 end) as bigint) as weekend_trip_count,
  cast(sum(case when is_peak_commute then 1 else 0 end) as bigint) as peak_commute_trip_count,
  cast(sum(case when is_airport_trip then 1 else 0 end) as bigint) as airport_trip_count,
  cast(sum(case when is_inter_borough_trip then 1 else 0 end) as bigint) as inter_borough_trip_count,
  cast(sum(case when is_intra_borough_trip then 1 else 0 end) as bigint) as intra_borough_trip_count,
  cast(sum(case when has_unmapped_pu_zone or has_unmapped_do_zone then 1 else 0 end) as bigint) as unmapped_zone_trip_count,
  cast(sum(total_amount) as double) as total_amount_sum,
  cast(avg(total_amount) as double) as avg_total_amount,
  cast(percentile_approx(total_amount, 0.5) as double) as median_total_amount,
  cast(percentile_approx(total_amount, 0.9) as double) as p90_total_amount,
  cast(percentile_approx(total_amount, 0.95) as double) as p95_total_amount,
  cast(avg(trip_distance) as double) as avg_trip_distance,
  cast(percentile_approx(trip_distance, 0.5) as double) as median_trip_distance,
  cast(percentile_approx(trip_distance, 0.9) as double) as p90_trip_distance,
  cast(percentile_approx(trip_distance, 0.95) as double) as p95_trip_distance,
  cast(avg(case when is_valid_duration then trip_duration_minutes end) as double) as avg_trip_duration_minutes,
  cast(percentile_approx(trip_duration_minutes, 0.5) as double) as median_trip_duration_minutes,
  cast(percentile_approx(trip_duration_minutes, 0.9) as double) as p90_trip_duration_minutes,
  cast(percentile_approx(trip_duration_minutes, 0.95) as double) as p95_trip_duration_minutes,
  cast(avg(case when avg_speed_mph is not null then avg_speed_mph end) as double) as avg_speed_mph,
  cast(avg(case when tip_pct is not null then tip_pct end) as double) as avg_tip_pct,
  cast(sum(dq_warning_count) as bigint) as dq_warning_count_sum,
  cast(avg(case when is_valid_trip then 0.0 else 1.0 end) as double) as invalid_trip_rate,
  cast(avg(case when is_zero_tip then 1.0 else 0.0 end) as double) as zero_tip_rate,
  cast(avg(case when is_zero_distance then 1.0 else 0.0 end) as double) as zero_distance_rate,
  cast(avg(case when has_implausible_fare then 1.0 else 0.0 end) as double) as implausible_fare_rate,
  cast(avg(case when is_airport_trip then 1.0 else 0.0 end) as double) as airport_trip_rate,
  cast(avg(case when is_inter_borough_trip then 1.0 else 0.0 end) as double) as inter_borough_trip_rate,
  cast(avg(case when is_intra_borough_trip then 1.0 else 0.0 end) as double) as intra_borough_trip_rate,
  cast(avg(case when has_unmapped_pu_zone or has_unmapped_do_zone then 1.0 else 0.0 end) as double) as unmapped_zone_rate
from {{ ref('trips_v1') }}
group by service_type, pickup_year, pickup_month, pickup_date, season_name
