select
  cast(vendor_id as bigint) as vendor_id,
  cast(pickup_ts as timestamp) as pickup_ts,
  cast(dropoff_ts as timestamp) as dropoff_ts,
  cast(passenger_count as double) as passenger_count,
  cast(trip_distance as double) as trip_distance,
  cast(rate_code_id as double) as rate_code_id,
  cast(store_and_fwd_flag as string) as store_and_fwd_flag,
  cast(pu_location_id as bigint) as pu_location_id,
  cast(do_location_id as bigint) as do_location_id,
  cast(payment_type as bigint) as payment_type,
  cast(fare_amount as double) as fare_amount,
  cast(extra as double) as extra,
  cast(mta_tax as double) as mta_tax,
  cast(tip_amount as double) as tip_amount,
  cast(tolls_amount as double) as tolls_amount,
  cast(improvement_surcharge as double) as improvement_surcharge,
  cast(total_amount as double) as total_amount,
  cast(congestion_surcharge as double) as congestion_surcharge,
  cast(airport_fee as double) as airport_fee,
  cast(year(pickup_ts) as int) as pickup_year,
  cast(month(pickup_ts) as int) as pickup_month,
  cast(to_date(pickup_ts) as date) as pickup_date,
  cast(dayofweek(pickup_ts) as int) as dow,
  cast(case when dayofweek(pickup_ts) in (1, 7) then true else false end as boolean) as is_weekend
from {{ ref('yellow_tripdata_silver') }}
