name: 'nyc_taxi_lakehouse'
version: '1.0.0'

profile: 'nyc_taxi_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_lakehouse:
    bronze:
      +materialized: incremental
      +schema: bronze
      +file_format: delta
      +incremental_strategy: insert_overwrite
      +partition_by:
        - source_year
        - source_month
    silver:
      +materialized: table
      +schema: silver
      +file_format: delta
    gold:
      +materialized: table
      +schema: gold
      +file_format: delta
